### ISSUE TITLE
Operaciones básicas

### ISSUE THREAD

**Issue by DavidAJUMA** [Daavji00/Calculadora-#3]
Realizar operaciones básicas de números, sumar, restar, multiplicar y dividir.
Sería conveniente tenerlas separadas en funciones diferentes para más 
simplicidad.

**Comment by Daavji00** [comment]
La idea cambia ligeramente, se va a realizar con eval pero se ha de tener en cuenta que no es muy seguro pues pueden introducirse inyecciones. Esto tenerlo claro para cambiarlo más adelante, además de saber que implementarlo en servidores o páginas webs es muy poco seguro. Pero como es una simple calculadora para practicar se cambiará como mucho por la biblioteca numprex, pero más adelante.
